### ISSUE TITLE
Refactor regeneration of sitemap during cron run

### ISSUE THREAD

**Issue by alexfinnarn** [backdrop-contrib/xmlsitemap#32]
Issues #27 and #26 deal with the cron function not resetting variables that are expected to be reset after a cron run. 

In my limited testing of what a typical user would do, i.e. turn on several of the sitemap modules relating to content generation and create new nodes, the sitemap regenerated with the newly added nodes after a cron run. 

Right before xmlsitemap_cron(), there are a couple of todos mentioning improvements that could be done during the regeneration process. 

This ticket will improve the regeneration code while at the same time fixing/altering the tests relating to cron runs.

**Comment by alexfinnarn** [comment]
FAIL: XML sitemaps regenerated and flag cleared. xmlsitemap.test | 86

Happens after/during cron run.

**Comment by quicksketch** [comment]
I think this issue fixed in the combination of #83 and my follow-up in https://github.com/backdrop-contrib/xmlsitemap/issues/29#issuecomment-1204514739.

There are still several `@todo` items, but maybe we should handle each of those in separate issues? The primary issue of the cron tests failing has been resolved.
