### ISSUE TITLE
Hide xmlsitemap_i18n

### ISSUE THREAD

**Issue by bd0bd** [backdrop-contrib/xmlsitemap#35]
It does not work in BD 1.6.3

**Comment by alexfinnarn** [comment]
Hello @bd0bd, and thanks for reporting this issue. Do you have any more information on what is not working or steps to reproduce your error(s)?

**Comment by bd0bd** [comment]
Hello! XML sitemap node is activated but nodes pages are not listed in the map :smile:

**Comment by alexfinnarn** [comment]
So I downloaded Backdrop 1.6.3, installed this module, and I can see nodes in my sitemap. You do have to configure some items to get nodes to show up in your sitemap. No node types are included initially because the user needs a chance to only include what they want to instead of exposing all node types in the sitemap. 

To enable them per node type:

1. Once the module is installed, go to "admin/config/search/xmlsitemap/settings" and click the "Content" tab. 
2. You should see all your site's node types listed as "excluded".
3. To include a node type in your sitemap, click on the node type link, click on the "XML sitemap" tab, and set the node type to be included instead of excluded. 
4. Regenerate your sitemap to add the nodes to it.

Let me know if you still have an issue after following those steps.

**Comment by bd0bd** [comment]
Thank you!
Solved.

May be it is better to make nodes included instead of excluded by default.

**Comment by bd0bd** [comment]
Please look:

![xml](https://cloud.githubusercontent.com/assets/13515302/24291767/5f4c5696-109b-11e7-918c-24a35ffc8609.png)

**Comment by alexfinnarn** [comment]
@bd0bd I'm curious as to how you got that screenshot. I don't see the i18n module anywhere on the "List Modules" page, and even if it did show up, it should be in the XML Sitemap group. 

https://github.com/backdrop-contrib/xmlsitemap/blob/3b482e18c1d344fb7c9b678dccd6016e37479daf/xmlsitemap_i18n/xmlsitemap_i18n.info#L4 

Also, the machine name of the module is somehow showing up...can you make sure you have the 1.0.0 release version of the code? The other JS issue you reported is big enough for a point release, but I'd like to add this issue to it if there is something to fix.

**Comment by jenlampton** [comment]
If you haven't already...  You could also add `hidden = TRUE` to the .info file if you want to hide the unsupported submodules on the modules page until they are ready

**Comment by alexfinnarn** [comment]
seems more appropriate to add the hidden property than to comment out the lines in the info file.
